language: python
python:
    - 2.7
    - 3.6
    - 3.7
branches:
    only:
        - master
        - /^\d\.\d+$/

env:
    - TOXENV=py27
    - TOXENV=py36
    - TOXENV=py37

addons:
    apt:
        packages:
            - libfreetype6-dev
            - liblcms2-dev
            - libffi-dev

install:
    - pip install -U pip wheel tox

script: tox

cache:
    directories:
        - $HOME/.cache/pip
