language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
#  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install 'docopt >= 0.5' --use-mirrors
  - pip install git+git://github.com/ojii/pymaging.git@74f62a706cfd19140a2cfbbb9a191af9cfd14044#egg=pymaging
  - pip install 'Pillow >= 2.0' --use-mirrors
  - pip install packbits --use-mirrors
  - python setup.py install

# command to run tests, e.g. python setup.py test
script: py.test
