language: python
python: 3.5
sudo: false
branches:
    only:
        - master
        - /^\d\.\d+$/

env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy

addons:
    apt:
        packages:
            - libfreetype6-dev
            - liblcms2-dev
            - libffi-dev

install:
    - pip install -U pip wheel tox

script: tox

cache:
    directories:
        - $HOME/.cache/pip
