; this is a tox config for running psd-tools tests
; under different Python interpreters

[tox]
envlist = clean,py27,py35,py36,py37,py38,report

[testenv]
commands = py.test --cov=psd_tools --cov-append --cov-report=term []
deps=
    pytest
    pytest-cov
    ipython
    cython
depends =
    {py27,py35,py36,py37,py38}: clean
    report: py27,py35,py36,py37,py38

[testenv:report]
deps = coverage
skip_install = true
commands = coverage report

[testenv:clean]
deps = coverage
skip_install = true
commands = coverage erase
